# Overlay Development Image for TurtleBot3 Simulation
FROM afrl_base:latest

# Create an overlay Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p /overlay_ws/src \
 && cd /overlay_ws \ 
 && catkin_init_workspace
RUN source /opt/ros/noetic/setup.bash \
 && cd /overlay_ws \
 && catkin build -j4

# Set up the work directory and entrypoint
WORKDIR /overlay_ws
COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]

